return {
    -- -- Set lualine as statusline
    -- "nvim-lualine/lualine.nvim",
    -- -- See `:help lualine.txt`
    -- --
    -- event = "VeryLazy",
    -- opts = function()
    --     local config = require("config")
    --     local icons = config.icons
    --
    --     return {
    --         options = {
    --             icons_enabled = false,
    --             component_separators = "|",
    --             section_separators = "",
    --         },
    --
    --         sections = {
    --             lualine_c = {
    --                 {
    --                     "filename",
    --                     path = 1,
    --                 },
    --             },
    --         },
    --     }
    -- end
}
